### ISSUE TITLE
Is there a faster way to upload models to Fooocus instead of the checkpoints folder?

### ISSUE THREAD

**Issue by GilFitussi** [ai-dock/fooocus#1]
First This is an amazing repo! 
I’m trying to upload models to Fooocus and was wondering if there’s a quicker method than placing them in the checkpoints folder. 
Any suggestions or alternative methods would be greatly appreciated!

Thanks for all your hard work!

**Comment by robballantyne** [comment]
Thank you!

Best way is to download from within the instance direct from Huggingface.  You can automate with a provisioning script - https://github.com/ai-dock/base-image/wiki/4.0-Running-the-Image#provisioning-script

Check out my A1111 or ComfyUI repos for the best examples

**Comment by GilFitussi** [comment]
Great job! Everything’s working like a charm!
